dir.create("raw_data")
dir.create("clean_data")
dir.create("scripts")
dir.create("results")
getwd()
dir.create("plots")
patient_info <- read.csv(file.choose())
str(patient_info)
View(patient_info)
class(patient_info$gender)
patient_info$gender <- as.factor(patient_info$gender)
class(patient_info$gender)
class(patient_info$diagnosis)
patient_info$diagnosis <- as.factor(patient_info$diagnosis)
class(patient_info$diagnosis)
patient_info$smoker <- as.factor(patient_info$smoker)
str(patient_info)
patient_info$smoking_status <- ifelse(patient_info$smoker == "Yes", 1, 0)
View(patient_info)
str(patient_info)
patient_info$smoking_status <- as.factor(patient_info$smoking_status)
str(patient_info)
write.csv(patient_info, file = "clean_data/patient_info_clean.csv")
